### ISSUE TITLE
Error from getlastblockheader [   Error: read ECONNRESET

### ISSUE THREAD

**Issue by wbz7** [scala-network/scala-pool#2]
root1@n1:~/pool$ node init.js
2020-09-26 22:46:20 [init] Starting Stellite Node.JS pool version 1.5.0
2020-09-26 22:46:20 [init] Api spawned on 1 thread(s)
2020-09-26 22:46:20 [init] Pool spawned on 4 thread(s)
2020-09-26 22:46:21 [poolWorker] Clear values for port %d in redis database.
2020-09-26 22:46:21 [chartsDataCollector] Started
/home/root1/pool/lib/model/Payee.js:123
module.exports =

SyntaxError: Unexpected end of input
    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/root1/pool/lib/paymentProcessor.js:33:15)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
2020-09-26 22:46:21 [unlocker] Started
2020-09-26 22:46:21 [init] Payment processor died, spawning replacement...
2020-09-26 22:46:21 [poolWorker] Error from getlastblockheader [
  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
]

**Comment by ahmyi** [comment]
What version of node you using? I advice to use current stable..
```JS
nvm install stable
```

**Comment by wbz7** [comment]
> What version of node you using? I advice to use current stable..
> 
> ```js
> nvm install stable
> ```

same error

**Comment by ahmyi** [comment]
Didn't get the error issued. I pushed some possible fixes. Can you try it out?

**Comment by wbz7** [comment]
> Didn't get the error issued. I pushed some possible fixes. Can you try it out?

root1@n1:~/scala-pool$ node init.js
2020-09-28 07:15:11 [init] Starting Stellite Node.JS pool version 1.5.0
2020-09-28 07:15:11 [init] Pool spawned on 1 thread(s)
2020-09-28 07:15:11 [init] Api spawned on 1 thread(s)
2020-09-28 07:15:12 [unlocker] Started
2020-09-28 07:15:12 [chartsDataCollector] Started
2020-09-28 07:15:12 [poolWorker] Clear values for port 3333 in redis database.
2020-09-28 07:15:12 [payments] Started
2020-09-28 07:15:12 [poolWorker] No reponse from getinfo [ null ]
2020-09-28 07:15:12 [api] API started & listening on 127.0.0.1 port 8118
2020-09-28 07:15:13 [pool] (Thread 1) Block template not avaliable null
2020-09-28 07:15:13 [poolWorker] No reponse from getinfo [ null ]
2020-09-28 07:15:14 [pool] (Thread 1) Block template not avaliable null
2020-09-28 07:15:14 [poolWorker] No reponse from getinfo [ null ]
2020-09-28 07:15:15 [pool] (Thread 1) Block template not avaliable null
2020-09-28 07:15:15 [poolWorker] No reponse from getinfo [ null ]
2020-09-28 07:15:16 [pool] (Thread 1) Block template not avaliable null

**Comment by ahmyi** [comment]
Can you try to remove `--restricted-rpc` from daemon
