### ISSUE TITLE
error JSON

### ISSUE THREAD

**Issue by w22w1** [scala-network/scala-pool#4]
hello, i have this error
2021-01-12 23:53:03 [poolWorker] Error from getlastblockheader [
  SyntaxError: Unexpected token < in JSON at position 0
      at JSON.parse (<anonymous>)
      at IncomingMessage.<anonymous> (/home/pool/pool/lib/apiInterfaces.js:37:35)
      at IncomingMessage.emit (events.js:201:15)
      at endReadableNT (_stream_readable.js:1130:12)
      at processTicksAndRejections (internal/process/task_queues.js:83:17)
]
2021-01-12 23:53:03 [pool] (Thread 3) Block template not avaliable null
2021-01-12 23:53:03 [pool] (Thread 1) Block template not avaliable null
2021-01-12 23:53:04 [pool] (Thread 4) Block template not avaliable null

**Comment by ahmyi** [comment]
Can i have your node version?

**Comment by w22w1** [comment]
12.0.0

**Comment by w22w1** [comment]
and with 15.5.1 don't work too

**Comment by ahmyi** [comment]
Try 14.x.x
